sonar.projectKey=03loveslollipop_cdp_2026
sonar.organization=03loveslollipop
sonar.sources=mlops_pipeline/src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
